import {
  Box,
  Infinity,
  Server,
  Github,
  Layers,
  Cloud,
  Code2,
  Terminal,
  Database,
  Cpu,
  Workflow
} from 'lucide-react';

export const NAV_LINKS = [
  { name: 'About', href: '#about' },
  { name: 'Skills', href: '#skills' },
  { name: 'Projects', href: '#projects' },
  { name: 'Certificates', href: '#certificates' },
  { name: 'Experience', href: '#experience' },
  { name: 'Blog', href: '#blog' },
  { name: 'Contact', href: '#contact' },
];

export const CONTACT_INFO = {
  email: 'bittush9534@gmail.com',
  location: 'New Delhi, India',
  linkedin: 'https://www.linkedin.com/in/bittu-kumar-54ab13254/',
  github: 'https://github.com/bittush8789',
  instagram: 'https://www.instagram.com/bittush8789/',
  hashnode: 'https://bittublog.hashnode.dev/',
};

export const REMOTE_SERVICES = [
  {
    title: 'LLMOps Engineer',
    description: 'Architecting production-grade LLM systems with Retrieval Augmented Generation (RAG), vector databases, and real-time observability.',
    icon: 'Cpu',
    tags: ['LangChain', 'Pinecone', 'LlamaIndex'],
  },
  {
    title: 'MLOps Engineer',
    description: 'Engineering end-to-end ML lifecycles—from automated training pipelines and versioning to scalable model serving and monitoring.',
    icon: 'Workflow',
    tags: ['Kubeflow', 'MLflow', 'DVC'],
  },
  {
    title: 'AI Engineer',
    description: 'Developing intelligent agentic systems and custom AI solutions that solve complex business challenges at scale.',
    icon: 'Box',
    tags: ['Agentic AI', 'PyTorch', 'Transformers'],
  },
  {
    title: 'DevOps Engineer',
    description: 'Building resilient, automated infrastructure using IaC and Kubernetes to support high-scale distributed applications.',
    icon: 'Cloud',
    tags: ['Kubernetes', 'Terraform', 'Helm'],
  },
];

export const CERTIFICATES = [
  {
    title: 'OCI 2025 Certified DevOps Professional',
    issuer: 'Oracle University',
    date: '2025',
    link: 'https://catalog-education.oracle.com/ords/certview/sharebadge?id=34AC35A9AEA21083794F856492091CE23B71B82C30060C6E29685DD4C9E591AD',
    category: 'Cloud/DevOps',
  },
  {
    title: 'MLOps Training & Certification',
    issuer: 'EXL Service India Pvt. Ltd.',
    date: '2024',
    link: 'https://www.linkedin.com/feed/update/urn:li:activity:7285340877634392066/',
    category: 'MLOps',
  },
  {
    title: 'LFS147: Introduction to AI/ML Toolkits with Kubeflow',
    issuer: 'The Linux Foundation',
    date: '2024',
    link: 'https://www.credly.com/badges/ff921ead-00e2-46c5-a45d-e733b4a08138/linked_in_profile',
    category: 'MLOps',
  },
  {
    title: 'Docker – Level 1',
    issuer: 'KodeKloud Engineer',
    date: '2023',
    link: 'https://engineer.kodekloud.com/certificate-verification/72aaa4dd-7c9c-47a4-903d-7eab4e4b76bd',
    category: 'DevOps',
  },
  {
    title: 'Kubernetes – Level 1',
    issuer: 'KodeKloud Engineer',
    date: '2023',
    link: 'https://engineer.kodekloud.com/certificate-verification/3cee0cd3-3868-4c7b-9ad5-65ef8a303e88',
    category: 'DevOps',
  },
];

export const BLOG_POSTS = [
  {
    title: 'Architecting a production-grade LLM pipeline with LangChain',
    excerpt: 'Step-by-step guide on building a RAG system that scales from proof-of-concept to production workloads using Pinecone and LangSmith.',
    date: 'March 2024',
    readTime: '12 min',
    link: 'https://bittublog.hashnode.dev/',
  },
  {
    title: 'Kubernetes Cost Optimization: Saving 40% on AWS EKS',
    excerpt: 'Practical strategies for managing resource limits, using Spot instances, and optimizing node groups for real-world CI/CD workflows.',
    date: 'February 2024',
    readTime: '8 min',
    link: 'https://bittublog.hashnode.dev/',
  },
  {
    title: 'GitOps Patterns with ArgoCD and Terraform',
    excerpt: 'How to manage your infrastructure and applications as code using the latest GitOps principles for high-velocity teams.',
    date: 'January 2024',
    readTime: '15 min',
    link: 'https://bittublog.hashnode.dev/',
  },
];

export const SKILLS = [
  {
    category: 'AI Engineering & Core',
    items: [
      { name: 'PyTorch & TensorFlow', icon: 'Cpu' },
      { name: 'Transformers (HF)', icon: 'Layers' },
      { name: 'Scikit-Learn', icon: 'Workflow' },
      { name: 'OpenAI / Gemini / Claude', icon: 'Cpu' },
      { name: 'Milvus & Qdrant', icon: 'Database' },
      { name: 'LlamaIndex', icon: 'Workflow' },
      { name: 'Pandas & NumPy', icon: 'Database' },
    ],
  },
  {
    category: 'MLOps & LLMOps',
    items: [
      { name: 'RAG & LangChain', icon: 'Workflow' },
      { name: 'LangSmith', icon: 'Cpu' },
      { name: 'Kubeflow & MLflow', icon: 'Workflow' },
      { name: 'Pinecone & Weaviate', icon: 'Database' },
      { name: 'DVC & Airflow', icon: 'Database' },
      { name: 'Evidently AI (Monitoring)', icon: 'Workflow' },
      { name: 'Weights & Biases', icon: 'Workflow' },
    ],
  },
  {
    category: 'DevOps & Infra',
    items: [
      { name: 'Docker & Kubernetes', icon: 'Box' },
      { name: 'Terraform & Pulumi', icon: 'Layers' },
      { name: 'Helm & Kustomize', icon: 'Box' },
      { name: 'AWS & Google Cloud', icon: 'Cloud' },
      { name: 'GitHub Actions', icon: 'Github' },
      { name: 'ArgoCD (GitOps)', icon: 'Infinity' },
      { name: 'Prometheus & Grafana Loki', icon: 'Cpu' },
    ],
  },
  {
    category: 'DevSecOps & Security',
    items: [
      { name: 'Snyk & Trivy', icon: 'ShieldCheck' },
      { name: 'SonarQube & Checkov', icon: 'Code2' },
      { name: 'HashiCorp Vault', icon: 'Lock' },
      { name: 'Aqua Security', icon: 'ShieldCheck' },
      { name: 'Istio Service Mesh', icon: 'Layers' },
      { name: 'FastAPI & Django', icon: 'Terminal' },
      { name: 'Linux Administration', icon: 'Terminal' },
    ],
  },
];

export const PROJECTS = [
  {
    title: 'Enterprise 3-Tier E-Commerce Platform',
    type: 'DevOps',
    problem: 'Architecting and deploying a production-grade 3-tier e-commerce architecture on Kubernetes. This platform integrates FastAPI backends, Next.js frontends, and robust data layers with Redis and PostgreSQL, all orchestrated via Terraform and Helm on AWS EKS to handle enterprise-scale traffic and security requirements.',
    stack: ['FastAPI', 'Next.js', 'PostgreSQL', 'Redis', 'Kubernetes', 'Terraform', 'AWS EKS', 'Helm'],
    features: [
      'High-availability 3-tier architecture',
      'Automated infrastructure with Terraform',
      'Helm-based application management',
      'Secure state management with Redis/Postgres',
    ],
    github: 'https://github.com/bittush8789/3-tier-ecommerce-platform',
    image: '/ecommerce-platform.png',
    isFeatured: true,
  },
  {
    title: 'CloudOps Control Center',
    type: 'DevOps',
    problem: 'Building a centralized dashboard for multi-cloud infrastructure management and observability. This control center provides a unified interface for monitoring Kubernetes clusters, managing CI/CD pipelines, and automating resource provisioning across AWS and Azure, reducing operational complexity for cloud-native teams.',
    stack: ['React', 'Node.js', 'Kubernetes API', 'Prometheus', 'Grafana', 'Terraform', 'GitHub Actions'],
    features: [
      'Unified Multi-Cloud Dashboard',
      'Real-time K8s Resource Monitoring',
      'Automated Pipeline Management',
      'Infrastructure Drift Detection',
    ],
    github: 'https://github.com/bittush8789/cloudops-control-center',
    image: '/cloudops-control.png',
    isFeatured: true,
  },
  {
    title: 'AWS Multi-Environment Terraform Platform',
    type: 'DevOps',
    problem: 'Architecting a modular, enterprise-ready AWS infrastructure platform using Terraform. The solution implements multi-environment (Dev/Staging/Prod) isolation, automated state management, and strict security compliance, ensuring consistency and reliability across complex cloud deployments.',
    stack: ['Terraform', 'AWS (VPC/EKS/RDS)', 'Terragrunt', 'GitHub Actions', 'Checkov', 'Infracost'],
    features: [
      'Modular Multi-Environment IaC',
      'Automated Security Scanning',
      'State Locking with DynamoDB/S3',
      'Cost Optimization Reporting',
    ],
    github: 'https://github.com/bittush8789/aws-infra-terraform-platform',
    image: '/aws-terraform.png',
    isFeatured: true,
  },
  {
    title: 'Production Kubernetes Monitoring Stack',
    type: 'DevOps',
    problem: 'Implementing a comprehensive observability suite for large-scale Kubernetes clusters. This project features a full Prometheus and Grafana stack, integrated with Loki for logging and Tempo for distributed tracing, providing deep insights into application performance and infrastructure health.',
    stack: ['Prometheus', 'Grafana', 'Loki', 'Tempo', 'Helm', 'Kubernetes', 'Alertmanager'],
    features: [
      'Full Observability Stack (METLT)',
      'Custom SRE Dashboards',
      'Proactive Alerting System',
      'Centralized Log Management',
    ],
    github: 'https://github.com/bittush8789/Kubernetes-Monitoring',
    image: '/k8s-monitoring.png',
    isFeatured: true,
  },
  {
    title: 'Enterprise DevSecOps Security Pipeline',
    type: 'DevSecOps',
    problem: 'Transforming standard CI/CD workflows into hardened DevSecOps pipelines. By integrating automated vulnerability scanning (Trivy), static analysis (SonarQube), and secret detection (TruffleHog), this pipeline ensures that security is shifted left and maintained throughout the entire software development lifecycle.',
    stack: ['GitHub Actions', 'Jenkins', 'Trivy', 'SonarQube', 'Snyk', 'TruffleHog', 'Docker'],
    features: [
      'Automated Vulnerability Scanning',
      'Static Analysis & Quality Gates',
      'Secret and License Compliance',
      'Hardened Container Image Builds',
    ],
    github: 'https://github.com/bittush8789/DevSecOps-CI-CD-Security-Pipeline',
    image: '/devsecops-pipeline.png',
    isFeatured: true,
  },
  {
    title: 'Advanced K8s Deployment Strategies',
    type: 'DevOps',
    problem: 'Developing a production-ready platform to execute and monitor advanced Kubernetes deployment strategies. This project demonstrates hands-on implementation of Blue-Green, Canary, and Progressive Delivery patterns using Argo Rollouts and Istio, enabling zero-downtime releases and automated rollbacks based on health metrics.',
    stack: ['Kubernetes', 'Argo Rollouts', 'Istio', 'Prometheus', 'Helm', 'Kind'],
    features: [
      'Blue-Green & Canary Deployments',
      'Progressive Delivery Automation',
      'Metrics-based Automated Rollbacks',
      'Service Mesh Integration',
    ],
    github: 'https://github.com/bittush8789/deployment-strategy',
    image: '/deployment-strategy.png',
    isFeatured: true,
  },
  {
    title: 'US Visa Approval Prediction',
    type: 'MLOps',
    problem: 'Architecting a production-scale MLOps environment to automate the lifecycle of US Visa prediction models. This implementation features robust data versioning with DVC, automated CI/CD via GitHub Actions, and scalable model serving using Kserve on Kubernetes, ensuring high availability and reproducible experiments across distributed teams.',
    stack: ['Python', 'Docker', 'AWS (S3/ECR)', 'MLflow', 'DVC', 'GitHub Actions', 'ArgoCD', 'Prometheus', 'Grafana'],
    features: [
      'Automated End-to-End MLOps Pipeline',
      'Data & Model Versioning with DVC',
      'GitOps-based deployment on Kubernetes',
      'Real-time system & model monitoring',
    ],
    github: 'https://github.com/bittush8789/us-visa-mlops',
    image: '/us-visa.png',
    isFeatured: true,
  },
  {
    title: 'Churn Model Prediction',
    type: 'MLOps',
    problem: 'Developing an end-to-end predictive system for customer churn that integrates advanced machine learning with production-grade monitoring. The project focuses on building a self-healing infrastructure that tracks model drift in real-time using Prometheus and Grafana, enabling proactive updates to maintain prediction accuracy in dynamic market conditions.',
    stack: ['Python', 'Scikit-Learn', 'Docker', 'Kubernetes', 'FastAPI', 'Prometheus', 'Grafana'],
    features: [
      'End-to-end MLOps pipeline for model inference',
      'Model monitoring and performance tracking',
      'Automated deployment and scaling on Kubernetes',
    ],
    github: 'https://github.com/bittush8789/Realtime-MLOps-Project',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
  },
  {
    title: 'MLOps Zero to Hero',
    type: 'MLOps',
    problem: 'A structured, industry-aligned roadmap designed to guide engineers through the complexities of modern MLOps. This comprehensive resource covers everything from containerization and orchestration to advanced LLMOps patterns, providing hands-on implementation guides for building resilient, cloud-native AI infrastructure from the ground up.',
    stack: ['MLOps Roadmap', 'Best Practices', 'System Design', 'Cloud Architecture'],
    features: [
      'Step-by-step learning path for MLOps engineers',
      'Hands-on projects and implementation guides',
      'Curated resources for LLMOps and Cloud-Native AI',
    ],
    github: 'https://github.com/bittush8789/mlops-zero-to-hero-',
    image: 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?auto=format&fit=crop&q=80&w=800',
    isFeatured: true,
  },
  {
    title: 'Medical Chatbot with LLMs & LangChain',
    type: 'LLMOps',
    problem: 'Implementing a secure, HIPAA-conscious medical chatbot using Retrieval Augmented Generation (RAG) and open-source LLMs. The system leverages Pinecone for high-performance vector search and LangChain for complex chain management, all deployed within an AWS-based containerized environment to ensure scalability and low-latency responses.',
    stack: ['LLMs', 'LangChain', 'Pinecone', 'Flask', 'AWS', 'Docker'],
    features: [
      'RAG implementation for medical knowledge retrieval',
      'Vector database integration with Pinecone',
      'Scalable deployment on AWS infrastructure',
    ],
    github: 'https://github.com/bittush8789/Build-a-Complete-Medical-Chatbot-with-LLMs-LangChain-Pinecone-Flask-AWS',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800',
  },
  {
    title: 'End-to-End ML Pipeline',
    type: 'MLOps',
    problem: 'Designing a fully automated CI/CD pipeline specialized for machine learning workloads. This project demonstrates the seamless integration of MLflow for experiment tracking and DVC for data provenance, enabling a "push-to-deploy" workflow that handles training, validation, and containerized deployment with zero-downtime on Kubernetes clusters.',
    stack: ['Python', 'MLflow', 'DVC', 'Docker', 'Kubernetes', 'GitHub Actions'],
    features: [
      'CI/CD for machine learning models',
      'Experiment tracking and model versioning',
      'Automated scaling and monitoring on Kubernetes',
    ],
    github: 'https://github.com/bittush8789/mlops-end-to-end-ml-pipeline',
    image: 'https://images.unsplash.com/photo-1518186285589-2f7649de83e0?auto=format&fit=crop&q=80&w=800',
  },
  {
    title: 'US Plumbing Solutions',
    type: 'DevOps',
    problem: 'Developing a robust, scalable full-stack booking and management system for a US-based services company, featuring automated deployments and secure client management.',
    stack: ['React', 'Node.js', 'Postgres', 'Docker', 'AWS', 'GitHub Actions'],
    features: [
      'Interactive booking and scheduling system',
      'Automated CI/CD pipeline for cloud deployment',
      'Secure client management and payment integration',
    ],
    github: 'https://github.com/bittush8789/Full-stack-US-based-plumbing-company',
    image: '/plumbing.png',
  },
  {
    title: 'Food Delivery Infrastructure',
    type: 'DevOps',
    problem: 'Architecting a highly available, containerized delivery ecosystem with multi-stage CI/CD pipelines and automated scaling to handle high-traffic workloads.',
    stack: ['React', 'Node.js', 'Redis', 'Docker', 'Kubernetes', 'GitHub Actions', 'AWS'],
    features: [
      'High-concurrency ordering system with Redis',
      'Multi-stage CI/CD for staging/production',
      'Auto-scaling Kubernetes Cluster deployment',
    ],
    github: 'https://github.com/bittush8789/fullstack-food-delivery-app',
    image: '/food-delivery.png',
  },
  {
    title: 'AI Blog Engine',
    type: 'LLMOps',
    problem: 'Deploying and managing an AI-driven content platform with automated model inference pipelines, cloud storage integration, and scalable web infrastructure.',
    stack: ['Python', 'Django', 'Docker', 'AWS (Lambda/S3)', 'Terraform', 'GitHub Actions'],
    features: [
      'Automated AI-content generation pipelines',
      'Infrastructure-as-Code (IaC) with Terraform',
      'Serverless scaling for AI inference tasks',
    ],
    github: 'https://github.com/bittush8789/AI-Blog-Generator-Platform',
    image: '/ai-blog.png',
  },
  {
    title: 'HealthConnect (Production SKU)',
    type: 'DevOps',
    problem: 'Engineering a high-availability healthcare appointment platform with production-ready patterns, automated SSL/TLS termination, and resilient microservices architecture.',
    stack: ['React', 'Node.js', 'MongoDB', 'Nginx', 'Docker Swarm', 'GitHub Actions'],
    features: [
      'Production-grade microservices with Nginx Proxy',
      'Automated SSL/TLS and secure session handling',
      'High-concurrency appointment scheduling system',
    ],
    github: 'https://github.com/bittush8789/production-ready-Healthcare-Appointment-Booking-Website',
    image: '/healthcare.png',
  },
  {
    title: 'AI DevOps Copilot',
    type: 'LLMOps',
    problem: 'Bridging the gap between generative AI and infrastructure management by building an intelligent assistant for DevOps troubleshooting. The copilot uses RAG to analyze logs and cloud configurations, providing automated root-cause analysis and Infrastructure-as-Code suggestions to reduce Mean Time to Recovery (MTTR) in complex microservices environments.',
    stack: ['Python', 'OpenAI/Gemini', 'LangChain', 'Terraform', 'Kubernetes'],
    features: [
      'AI-driven infrastructure provisioning and optimization',
      'Automated troubleshooting and log analysis',
      'Natural language interface for DevOps operations',
    ],
    github: 'https://github.com/bittush8789/AI-DevOps-Copilot',
    image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&q=80&w=800',
  },
  {
    title: 'AI-Powered DevOps Projects',
    type: 'DevOps',
    problem: 'Exploring the intersection of artificial intelligence and site reliability engineering through a series of automated pilot projects. Key implementations include predictive scaling algorithms for AWS EC2/EKS and self-healing CI/CD pipelines that use LLMs to automatically patch common dependency vulnerabilities and configuration drifts.',
    stack: ['Python', 'GitHub Actions', 'Docker', 'AI/ML Models', 'AWS'],
    features: [
      'Self-healing CI/CD pipelines',
      'Predictive resource scaling and management',
      'Automated security vulnerability patching',
    ],
    github: 'https://github.com/bittush8789/AI-Powered-DevOps-projects-',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=800',
  },
  {
    title: 'Modern Resume & Portfolio Builder',
    type: 'DevOps',
    problem: 'Developing a high-performance, developer-centric portfolio engine that automates the generation of resumes and project showcases. Built with a focus on core web vitals and premium aesthetics, the application uses React and Framer Motion to deliver a "Liquid Glass" experience, serving as a template for technical professionals to showcase complex skillsets.',
    stack: ['React', 'Tailwind CSS', 'Framer Motion', 'TypeScript', 'Vite'],
    features: [
      'Dynamic resume generation for different roles',
      'Interactive project showcase with filtering',
      'Responsive, high-performance portfolio design',
    ],
    github: 'https://github.com/bittush8789/modern-Resume-and-Portfolio-Builder',
    image: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=800',
  },
];

export const EXPERIENCE = [
  {
    role: 'MLOps Engineer',
    company: 'EXL Service India Pvt. Ltd. – Noida',
    period: 'April 2024 – Present',
    description: 'Independently architecting and deploying scalable ML/LLM systems across distributed cloud environments with production-grade pipelines and end-to-end lifecycle management.',
    achievements: [
      'Designed and implemented end-to-end MLOps workflows covering model training, versioning, deployment, serving, scaling, and lifecycle management — fully automated for async, remote-first operations.',
      'Built and productionized ML models with clear separation between model logic, serving layer, and infrastructure, enabling independent ownership across distributed teams.',
      'Implemented custom model serving using Flask with Gunicorn (WSGI) and evaluated against KServe-managed serving, documenting scalability and operational trade-offs for cross-team reference.',
      'Containerized ML workloads using Docker to ensure reproducible builds and immutable artifacts across multiple cloud environments.',
      'Deployed ML models on Kubernetes using Deployments, Services, and Ingress for scalable, self-healing inference — zero-touch deployments via GitOps.',
      'Implemented KServe-based model serving using standardized inference APIs, enabling seamless handoffs between remote ML and platform teams.',
      'Integrated external model artifact storage using AWS S3 and HTTP-based endpoints for globally accessible model registries.',
      'Configured SageMaker Domain, User Profiles, and IAM execution roles for secure, multi-tenant ML environments supporting remote data science teams.',
      'Designed IAM-based role separation for Data Scientists, ML Engineers, and MLOps Engineers — enforcing least-privilege access across distributed teams.',
      'Automated model training, artifact generation, and deployment readiness using Kubeflow pipelines, reducing manual intervention and enabling async workflow execution.',
      'Maintained comprehensive documentation and runbooks for all ML infrastructure, ensuring smooth knowledge transfer across time zones.',
    ],
  },
  {
    role: 'DevOps Engineer',
    company: 'EXL Service India Pvt. Ltd. – Noida',
    period: 'April 2024 – Present',
    description: 'Independently managing cloud infrastructure, CI/CD automation, and production reliability for distributed development teams across multiple projects.',
    achievements: [
      'Streamlined CI/CD pipelines for Java-based applications using Gradle, achieving a 20% reduction in build and deployment time — enabling faster async release cycles.',
      'Containerized microservices architecture, supporting services for 2 distributed development teams with self-service deployment capabilities.',
      'Drove Kubernetes adoption across teams, contributing to 20% cost efficiency through right-sizing and spot instance strategies.',
      'Implemented Infrastructure as Code using Terraform for microservices and Kubernetes infrastructure on AWS, enabling reproducible environments across teams.',
      'Hands-on experience with AWS networking (VPC, ALB, Route53, IAM), integrating Route53 with ALB for custom domains in Kubernetes and resolving critical VPC peering issues.',
      'Introduced Git best practices and branching strategies, improving collaboration and traceability for remote-first development teams.',
      'Mentored junior DevOps engineers remotely on Kubernetes onboarding, PoCs, and CI/CD automation — conducted async knowledge-sharing sessions.',
      'Resolved critical production incidents independently, ensuring system availability and minimizing business impact with detailed post-mortem documentation.',
      'Implemented Kubernetes Ingress for multiple microservices and set up Terraform remote backend with S3/DynamoDB state locking for multi-team state management.',
      'Leveraged AI tools to accelerate automation, troubleshooting, and documentation — maintaining a self-driven, high-output remote work style.',
    ],
  },
];
